### PR TITLE
call: make dial timeout configurable

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Hello @tmakkonen!

10s is far too short for us, so I've made it configurable.

Best,
AK

**Review by htriem — APPROVED** [review]
LGTM! :+1:

**Comment by soroshsabz** [comment]
ITNOA

@tmakkonen Any plan for merge this PR?

**Comment by soroshsabz** [comment]
@tmakkonen  Thanks

**Pull request merged**
